### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by kimdre**
# Changes
- Changed the name of the README file and also the text format to modern markdown.
- Added a short documentation on how to receive the required `DN` in your FreeIPA LDAP tree.

### CODE REVIEW

**Comment by abbra** [comment]
Thank you for the update. I think you can actually combine these two commits into the same one. Could you please do that?

**Comment by kimdre** [comment]
You can combine them by doing a Squash Merge when you accept the Pull Request. 
image

**Comment by abbra** [comment]
We do not allow squash and merge, only rebases.

**Comment by kimdre** [comment]
Should be fixed now.

**Comment by abbra** [comment]
Thank you.

**Pull request merged**
